name: google_books
description: A library to help on the search for books on google books api
version: 0.0.1+1

environment:
  sdk: ">=2.15.0 <4.0.0"

dependencies:
  http: ">=1.0.0 <2.0.0"

dev_dependencies:
  lints: ^1.0.1
  test: ^1.16.8
